version: 2
jobs:
    build:
        working_directory: ~/autoprompt
        docker:
            - image: continuumio/miniconda3
        environment:
            OMP_NUM_THREADS: 1
        resource_class: medium
        parallelism: 1
        steps:
            - checkout
            - run: conda install python=3.7
            - run: conda install pytorch==1.4.0 cpuonly -c pytorch -y
            - run: pip install -e '.[test]'
            - run: python -m pytest --disable-warnings --junitxml=test-results/junit.xml
            - store_test_results:
                path: test-results
            - store_artifacts:
                path: test-results
        
