trainer: 'finetune'
args:
    seed: 0
    model_name: 'roberta-large'
    train: 'data/SuperFUGUE/CB/train.jsonl'
    dev: 'data/SuperFUGUE/CB/dev.jsonl'
    test: 'data/SuperFUGUE/CB/dev_all.jsonl'
    checklist: null
    label_map: '{"entailment": 0, "contradiction": 1, "neutral": 2}'
    label_field: 'label'
    input_field_a: 'premise'
    input_field_b: 'hypothesis'
    preprocessor: null 
    evaluation_strategy: 'classification'
    finetune_mode: []
    evaluation_metric: 'accuracy-macro-f1'
    skip_train: False
    skip_eval: False
    skip_test: False
    bsz: 2
    epochs: 30
    disable_dropout: False
    clip: 1.0
    limit: null
    force_overwrite: True
    quiet: False
    tmp: True
    finetune_lr: null
parameters:
    accumulation_steps: [1, 2, 4]
    lr: [1.0e-5, 2.0e-5, 5.0e-5]
